export type App = {
  id: string
  name: string
  description: string
  categories: string[]
  brew_cask?: string | null
  brew_formula?: string | null
  mas_id?: number | null
  dmg_url?: string | null
  install_script?: string | null
}

export const APPS: App[] = [
  { id: 'visual-studio-code', name: 'Visual Studio Code', description: 'Lightweight but powerful source code editor', categories: ['developer', 'editor'], brew_cask: 'visual-studio-code' },
  { id: 'cursor', name: 'Cursor', description: 'AI-first code editor built on VS Code', categories: ['developer', 'editor', 'ai'], brew_cask: 'cursor' },
  { id: 'iterm2', name: 'iTerm2', description: 'Replacement for Terminal with powerful features', categories: ['developer', 'terminal'], brew_cask: 'iterm2' },
  { id: 'warp', name: 'Warp', description: 'Modern AI-powered terminal', categories: ['developer', 'terminal', 'ai'], brew_cask: 'warp' },
  { id: 'git', name: 'Git', description: 'Distributed version control system', categories: ['developer', 'cli'], brew_formula: 'git' },
  { id: 'github-desktop', name: 'GitHub Desktop', description: 'Simple collaboration from your desktop', categories: ['developer', 'git'], brew_cask: 'github' },
  { id: 'tower', name: 'Tower', description: 'The most powerful Git client for Mac', categories: ['developer', 'git'], brew_cask: 'tower' },
  { id: 'homebrew', name: 'Homebrew', description: 'The missing package manager for macOS', categories: ['developer', 'cli'], install_script: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"' },
  { id: 'node', name: 'Node.js', description: "JavaScript runtime built on Chrome's V8", categories: ['developer', 'runtime'], brew_formula: 'node' },
  { id: 'python', name: 'Python', description: 'Interpreted, high-level programming language', categories: ['developer', 'runtime', 'data-science'], brew_formula: 'python' },
  { id: 'docker', name: 'Docker Desktop', description: 'Containerization platform for developers', categories: ['developer', 'devops'], brew_cask: 'docker' },
  { id: 'postman', name: 'Postman', description: 'API platform for building and testing APIs', categories: ['developer', 'api'], brew_cask: 'postman' },
  { id: 'insomnia', name: 'Insomnia', description: 'Open-source API client and design platform', categories: ['developer', 'api'], brew_cask: 'insomnia' },
  { id: 'tableplus', name: 'TablePlus', description: 'Modern, native database management tool', categories: ['developer', 'database'], brew_cask: 'tableplus', mas_id: 1247817819 },
  { id: 'sequel-pro', name: 'Sequel Pro', description: 'Fast, easy MySQL/MariaDB database management', categories: ['developer', 'database'], brew_cask: 'sequel-pro' },
  { id: 'redis-insight', name: 'RedisInsight', description: 'Visual tool for Redis databases', categories: ['developer', 'database'], brew_cask: 'redisinsight' },
  { id: 'sourcetree', name: 'Sourcetree', description: 'Free Git GUI for Mac', categories: ['developer', 'git'], brew_cask: 'sourcetree' },
  { id: 'jetbrains-toolbox', name: 'JetBrains Toolbox', description: 'Manage all JetBrains IDEs in one place', categories: ['developer', 'editor'], brew_cask: 'jetbrains-toolbox' },
  { id: 'xcode', name: 'Xcode', description: "Apple's IDE for macOS, iOS, and more", categories: ['developer', 'editor', 'ios'], mas_id: 497799835 },
  { id: 'sf-symbols', name: 'SF Symbols', description: "Apple's icon library for developers", categories: ['developer', 'designer', 'ios'], dmg_url: 'https://developer.apple.com/sf-symbols/' },
  { id: 'proxyman', name: 'Proxyman', description: 'Native macOS app for HTTP/HTTPS debugging', categories: ['developer', 'network'], brew_cask: 'proxyman' },
  { id: 'charles', name: 'Charles Proxy', description: 'HTTP proxy and monitor for debugging', categories: ['developer', 'network'], brew_cask: 'charles' },
  { id: 'figma', name: 'Figma', description: 'Collaborative interface design tool', categories: ['designer', 'design'], brew_cask: 'figma' },
  { id: 'sketch', name: 'Sketch', description: 'Digital design toolkit for Mac', categories: ['designer', 'design'], brew_cask: 'sketch' },
  { id: 'affinity-designer', name: 'Affinity Designer', description: 'Professional vector graphic design software', categories: ['designer', 'design'], mas_id: 824171161 },
  { id: 'affinity-photo', name: 'Affinity Photo', description: 'Professional photo editing software', categories: ['designer', 'photo'], mas_id: 824183456 },
  { id: 'adobe-creative-cloud', name: 'Adobe Creative Cloud', description: 'Hub for all Adobe creative apps', categories: ['designer', 'creative'], brew_cask: 'adobe-creative-cloud' },
  { id: 'pixelmator-pro', name: 'Pixelmator Pro', description: 'Professional image editing for Mac', categories: ['designer', 'photo'], mas_id: 1289583905 },
  { id: 'canva', name: 'Canva', description: 'Design anything with easy drag-and-drop tools', categories: ['designer', 'content-creator'], mas_id: 897446215 },
  { id: 'principle', name: 'Principle', description: 'Animated design tool for app prototypes', categories: ['designer', 'prototyping'], mas_id: 788839335 },
  { id: 'zeplin', name: 'Zeplin', description: 'Design handoff and style guide tool', categories: ['designer', 'developer'], brew_cask: 'zeplin' },
  { id: 'notion', name: 'Notion', description: 'All-in-one workspace for notes and collaboration', categories: ['productivity', 'notes'], brew_cask: 'notion', mas_id: 1559269364 },
  { id: 'obsidian', name: 'Obsidian', description: 'Knowledge base that works on local Markdown files', categories: ['productivity', 'notes'], brew_cask: 'obsidian' },
  { id: 'bear', name: 'Bear', description: 'Beautiful, flexible writing app for notes', categories: ['productivity', 'notes'], mas_id: 1091189122 },
  { id: '1password', name: '1Password', description: 'Password manager and secure digital wallet', categories: ['productivity', 'security'], brew_cask: '1password', mas_id: 1333542190 },
  { id: 'bitwarden', name: 'Bitwarden', description: 'Open source password manager', categories: ['productivity', 'security'], brew_cask: 'bitwarden', mas_id: 1352778147 },
  { id: 'alfred', name: 'Alfred', description: 'Productivity app with search and custom workflows', categories: ['productivity', 'launcher'], brew_cask: 'alfred' },
  { id: 'raycast', name: 'Raycast', description: 'Blazing fast, totally extendable launcher', categories: ['productivity', 'launcher', 'ai'], brew_cask: 'raycast' },
  { id: 'arc', name: 'Arc Browser', description: 'The browser that thinks differently', categories: ['productivity', 'browser'], brew_cask: 'arc' },
  { id: 'chrome', name: 'Google Chrome', description: "Fast, secure web browser by Google", categories: ['productivity', 'browser'], brew_cask: 'google-chrome' },
  { id: 'firefox', name: 'Firefox', description: 'Fast, private and safe web browser', categories: ['productivity', 'browser'], brew_cask: 'firefox' },
  { id: 'brave', name: 'Brave Browser', description: 'Privacy-focused browser with built-in ad blocking', categories: ['productivity', 'browser'], brew_cask: 'brave-browser' },
  { id: 'slack', name: 'Slack', description: 'Business communication platform', categories: ['productivity', 'communication'], brew_cask: 'slack', mas_id: 803453959 },
  { id: 'discord', name: 'Discord', description: 'Voice, video, and text communication platform', categories: ['productivity', 'communication'], brew_cask: 'discord' },
  { id: 'telegram', name: 'Telegram', description: 'Fast, secure, cloud-based messaging', categories: ['productivity', 'communication'], brew_cask: 'telegram', mas_id: 747648890 },
  { id: 'zoom', name: 'Zoom', description: 'Video conferencing and meetings platform', categories: ['productivity', 'communication'], brew_cask: 'zoom', mas_id: 617349475 },
  { id: 'linear', name: 'Linear', description: 'Streamlined project management for software teams', categories: ['productivity', 'project-management'], brew_cask: 'linear-linear' },
  { id: 'things3', name: 'Things 3', description: 'Award-winning personal task manager', categories: ['productivity', 'task-management'], mas_id: 904280696 },
  { id: 'todoist', name: 'Todoist', description: 'The to-do list to organize work and life', categories: ['productivity', 'task-management'], brew_cask: 'todoist', mas_id: 585829637 },
  { id: 'cleaner-one-pro', name: 'CleanMyMac X', description: 'macOS system cleaner and performance optimizer', categories: ['productivity', 'utility'], brew_cask: 'cleanmymac' },
  { id: 'bartender', name: 'Bartender', description: 'Organize your Mac menu bar apps', categories: ['productivity', 'utility'], brew_cask: 'bartender' },
  { id: 'rectangle', name: 'Rectangle', description: 'Move and resize windows in macOS using keyboard shortcuts', categories: ['productivity', 'window-management'], brew_cask: 'rectangle' },
  { id: 'magnet', name: 'Magnet', description: 'Keep your workspace organized with window snapping', categories: ['productivity', 'window-management'], mas_id: 441258766 },
  { id: 'mimestream', name: 'Mimestream', description: 'Native Gmail client for macOS', categories: ['productivity', 'email'], brew_cask: 'mimestream' },
  { id: 'spark', name: 'Spark Mail', description: 'Smart email app with AI features', categories: ['productivity', 'email'], mas_id: 1176895641 },
  { id: 'notion-calendar', name: 'Notion Calendar', description: 'Powerful calendar app integrating with Notion', categories: ['productivity', 'calendar'], brew_cask: 'notion-calendar' },
  { id: 'fantastical', name: 'Fantastical', description: 'Natural language calendar and reminders', categories: ['productivity', 'calendar'], brew_cask: 'fantastical', mas_id: 975937182 },
  { id: 'setapp', name: 'Setapp', description: 'Subscription service for Mac and iOS apps', categories: ['productivity', 'utility'], brew_cask: 'setapp' },
  { id: 'screenflow', name: 'ScreenFlow', description: 'Screen recording and video editing for Mac', categories: ['content-creator', 'video'], mas_id: 1475796517 },
  { id: 'loom', name: 'Loom', description: 'Async video messaging for work', categories: ['content-creator', 'video'], brew_cask: 'loom' },
  { id: 'davinci-resolve', name: 'DaVinci Resolve', description: 'Professional video editing, color, and audio', categories: ['content-creator', 'video'], brew_cask: 'davinci-resolve' },
  { id: 'final-cut-pro', name: 'Final Cut Pro', description: "Apple's professional video editing software", categories: ['content-creator', 'video'], mas_id: 424389933 },
  { id: 'obs', name: 'OBS Studio', description: 'Free and open source streaming and recording', categories: ['content-creator', 'streaming'], brew_cask: 'obs' },
  { id: 'cleanshot-x', name: 'CleanShot X', description: 'Screenshot and screen recording tool for Mac', categories: ['content-creator', 'productivity', 'screenshot'], brew_cask: 'cleanshot' },
  { id: 'imageoptim', name: 'ImageOptim', description: 'Lossless image compression and optimization', categories: ['developer', 'designer', 'image'], brew_cask: 'imageoptim' },
  { id: 'handbrake', name: 'HandBrake', description: 'Open source video transcoder', categories: ['content-creator', 'video'], brew_cask: 'handbrake' },
  { id: 'audacity', name: 'Audacity', description: 'Free, open source audio editor', categories: ['content-creator', 'audio'], brew_cask: 'audacity' },
  { id: 'logic-pro', name: 'Logic Pro', description: "Apple's professional music production studio", categories: ['content-creator', 'audio'], mas_id: 634148309 },
  { id: 'jupyter', name: 'JupyterLab Desktop', description: 'Desktop app for JupyterLab notebooks', categories: ['data-science', 'developer'], brew_cask: 'jupyterlab' },
  { id: 'r', name: 'R', description: 'Statistical computing language', categories: ['data-science'], brew_formula: 'r' },
  { id: 'rstudio', name: 'RStudio', description: 'IDE for R statistical computing', categories: ['data-science'], brew_cask: 'rstudio' },
  { id: 'anaconda', name: 'Anaconda', description: 'Python/R distribution for data science', categories: ['data-science', 'developer'], brew_cask: 'anaconda' },
  { id: 'pycharm', name: 'PyCharm', description: 'Python IDE by JetBrains', categories: ['data-science', 'developer', 'editor'], brew_cask: 'pycharm' },
  { id: 'datagrip', name: 'DataGrip', description: 'Database IDE by JetBrains', categories: ['data-science', 'developer', 'database'], brew_cask: 'datagrip' },
  { id: 'mongodb-compass', name: 'MongoDB Compass', description: 'GUI for exploring and querying MongoDB', categories: ['developer', 'database'], brew_cask: 'mongodb-compass' },
  { id: 'httpie', name: 'HTTPie', description: 'Modern API testing client with beautiful UI', categories: ['developer', 'api'], brew_cask: 'httpie' },
  { id: 'transmit', name: 'Transmit 5', description: 'The gold standard of Mac file transfer apps', categories: ['developer', 'ftp'], brew_cask: 'transmit' },
  { id: 'cyberduck', name: 'Cyberduck', description: 'FTP, SFTP, WebDAV, S3 file browser', categories: ['developer', 'ftp'], brew_cask: 'cyberduck', mas_id: 409222199 },
  { id: 'fork', name: 'Fork', description: 'Fast and friendly git client for Mac', categories: ['developer', 'git'], brew_cask: 'fork' },
  { id: 'dash', name: 'Dash', description: 'API documentation browser and code snippet manager', categories: ['developer'], brew_cask: 'dash' },
  { id: 'paw', name: 'RapidAPI (Paw)', description: 'Full-featured HTTP client for API testing', categories: ['developer', 'api'], brew_cask: 'rapidapi' },
  { id: 'virtualbox', name: 'VirtualBox', description: 'Free, open source VM platform', categories: ['developer', 'virtualization'], brew_cask: 'virtualbox' },
  { id: 'utm', name: 'UTM', description: 'Virtual machines for Mac (Apple Silicon native)', categories: ['developer', 'virtualization'], brew_cask: 'utm', mas_id: 1538878817 },
  { id: 'multipass', name: 'Multipass', description: 'Instant Ubuntu VMs on Mac', categories: ['developer', 'virtualization'], brew_cask: 'multipass' },
  { id: 'visual-paradigm', name: 'OmniGraffle', description: 'Diagramming and digital illustration for Mac', categories: ['designer', 'developer', 'diagramming'], brew_cask: 'omnigraffle' },
  { id: 'miro', name: 'Miro', description: 'Visual collaboration platform and whiteboard', categories: ['productivity', 'designer', 'collaboration'], brew_cask: 'miro' },
  { id: 'figma-agent', name: 'Figma Agent', description: 'Figma font helper for local font access', categories: ['designer'], brew_cask: 'figma' },
  { id: 'fontexplorer-x', name: 'FontExplorer X Pro', description: 'Professional font management for Mac', categories: ['designer'], brew_cask: 'fontexplorer-x-pro' },
  { id: 'textsoap', name: 'Typeface 3', description: 'Beautiful font manager for Mac', categories: ['designer'], brew_cask: 'typeface' },
  { id: 'screenium', name: 'Screenium', description: 'Advanced screenshot and annotation tool', categories: ['productivity', 'screenshot'], mas_id: 1511933600 },
  { id: 'paste', name: 'Paste', description: 'Smart clipboard manager for Mac', categories: ['productivity', 'clipboard'], brew_cask: 'paste', mas_id: 967805235 },
  { id: 'maccy', name: 'Maccy', description: 'Lightweight clipboard manager for macOS', categories: ['productivity', 'clipboard'], brew_cask: 'maccy' },
  { id: 'topnotch', name: 'TopNotch', description: 'Make the MacBook notch invisible', categories: ['productivity', 'utility'], mas_id: 1477063649 },
  { id: 'amphetamine', name: 'Amphetamine', description: 'Keep your Mac awake with ease', categories: ['productivity', 'utility'], mas_id: 937984704 },
  { id: 'dato', name: 'Dato', description: 'Menu bar calendar and time zone converter', categories: ['productivity', 'utility'], mas_id: 1470584107 },
  { id: 'stats', name: 'Stats', description: 'macOS system monitor in your menu bar', categories: ['productivity', 'utility'], brew_cask: 'stats' },
  { id: 'istatmenus', name: 'iStat Menus', description: 'Advanced Mac system monitor in the menu bar', categories: ['productivity', 'utility'], brew_cask: 'istatmenus', mas_id: 1319778037 },
  { id: 'superduper', name: 'SuperDuper!', description: 'Smart, fast backup and recovery for Mac', categories: ['productivity', 'backup'], brew_cask: 'superduper' },
  { id: 'carbon-copy-cloner', name: 'Carbon Copy Cloner', description: 'Backup, restore, and clone your Mac', categories: ['productivity', 'backup'], brew_cask: 'carbon-copy-cloner' },
  { id: 'dropbox', name: 'Dropbox', description: 'Cloud storage and file sharing', categories: ['productivity', 'storage'], brew_cask: 'dropbox' },
  { id: 'google-drive', name: 'Google Drive', description: "Google's cloud storage and sync", categories: ['productivity', 'storage'], brew_cask: 'google-drive' },
  { id: 'vlc', name: 'VLC', description: 'Free, open source cross-platform media player', categories: ['content-creator', 'media'], brew_cask: 'vlc' },
  { id: 'iina', name: 'IINA', description: 'Modern media player for macOS', categories: ['content-creator', 'media'], brew_cask: 'iina' },
  { id: 'spotify', name: 'Spotify', description: 'Digital music streaming service', categories: ['productivity', 'media'], brew_cask: 'spotify' },
  { id: 'gpg-suite', name: 'GPG Suite', description: 'OpenPGP encryption tools for macOS', categories: ['developer', 'security'], brew_cask: 'gpg-suite' },
  { id: 'tailscale', name: 'Tailscale', description: 'Zero config VPN built on WireGuard', categories: ['developer', 'network'], brew_cask: 'tailscale', mas_id: 1475387142 },
  { id: 'wireshark', name: 'Wireshark', description: 'Network protocol analyzer', categories: ['developer', 'network'], brew_cask: 'wireshark' },
]

export type Category = { id: string; label: string }

export const CATEGORIES: Category[] = [
  { id: 'all', label: 'All' },
  { id: 'developer', label: 'Developer' },
  { id: 'designer', label: 'Designer' },
  { id: 'productivity', label: 'Productivity' },
  { id: 'content-creator', label: 'Content Creator' },
  { id: 'data-science', label: 'Data Science' },
  { id: 'communication', label: 'Communication' },
  { id: 'utility', label: 'Utilities' },
  { id: 'browser', label: 'Browser' },
  { id: 'security', label: 'Security' },
  { id: 'ai', label: 'AI' },
]

export function getInstallMethod(app: App): 'brew' | 'mas' | 'dmg' | 'script' | null {
  if (app.brew_cask || app.brew_formula) return 'brew'
  if (app.mas_id) return 'mas'
  if (app.dmg_url) return 'dmg'
  if (app.install_script) return 'script'
  return null
}
