import Foundation

struct CatalogApp: Identifiable, Codable {
    let id: String
    let name: String
    let brewCask: String?
    let masId: Int?
    let categories: [String]
    var description: String {
        if let cask = brewCask {
            return "brew install --cask \(cask)"
        } else if let mas = masId {
            return "mas install \(mas)"
        }
        return id
    }
}

let allApps: [CatalogApp] = [
    CatalogApp(id: "visual-studio-code", name: "Visual Studio Code", brewCask: "visual-studio-code", masId: nil, categories: ["developer"]),
    CatalogApp(id: "cursor", name: "Cursor", brewCask: "cursor", masId: nil, categories: ["developer", "ai"]),
    CatalogApp(id: "iterm2", name: "iTerm2", brewCask: "iterm2", masId: nil, categories: ["developer"]),
    CatalogApp(id: "docker", name: "Docker Desktop", brewCask: "docker", masId: nil, categories: ["developer"]),
    CatalogApp(id: "warp", name: "Warp", brewCask: "warp", masId: nil, categories: ["developer"]),
    CatalogApp(id: "github", name: "GitHub Desktop", brewCask: "github", masId: nil, categories: ["developer"]),
    CatalogApp(id: "tableplus", name: "TablePlus", brewCask: "tableplus", masId: nil, categories: ["developer"]),
    CatalogApp(id: "postman", name: "Postman", brewCask: "postman", masId: nil, categories: ["developer"]),
    CatalogApp(id: "xcode", name: "Xcode", brewCask: nil, masId: 497799835, categories: ["developer"]),
    CatalogApp(id: "figma", name: "Figma", brewCask: "figma", masId: nil, categories: ["designer"]),
    CatalogApp(id: "sketch", name: "Sketch", brewCask: "sketch", masId: nil, categories: ["designer"]),
    CatalogApp(id: "canva", name: "Canva", brewCask: nil, masId: 897446215, categories: ["designer"]),
    CatalogApp(id: "notion", name: "Notion", brewCask: "notion", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "obsidian", name: "Obsidian", brewCask: "obsidian", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "rectangle", name: "Rectangle", brewCask: "rectangle", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "raycast", name: "Raycast", brewCask: "raycast", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "alfred", name: "Alfred", brewCask: "alfred", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "bear", name: "Bear", brewCask: nil, masId: 1091189122, categories: ["productivity"]),
    CatalogApp(id: "slack", name: "Slack", brewCask: "slack", masId: nil, categories: ["communication"]),
    CatalogApp(id: "discord", name: "Discord", brewCask: "discord", masId: nil, categories: ["communication"]),
    CatalogApp(id: "zoom", name: "Zoom", brewCask: "zoom", masId: nil, categories: ["communication"]),
    CatalogApp(id: "loom", name: "Loom", brewCask: "loom", masId: nil, categories: ["content-creator"]),
    CatalogApp(id: "obs", name: "OBS Studio", brewCask: "obs", masId: nil, categories: ["content-creator"]),
    CatalogApp(id: "davinci-resolve", name: "DaVinci Resolve", brewCask: "davinci-resolve", masId: nil, categories: ["content-creator"]),
    CatalogApp(id: "handbrake", name: "HandBrake", brewCask: "handbrake", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "imageoptim", name: "ImageOptim", brewCask: "imageoptim", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "iina", name: "IINA", brewCask: "iina", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "cleanshot", name: "CleanShot X", brewCask: "cleanshot", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "vlc", name: "VLC", brewCask: "vlc", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "spotify", name: "Spotify", brewCask: "spotify", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "arc", name: "Arc Browser", brewCask: "arc", masId: nil, categories: ["browser"]),
    CatalogApp(id: "chrome", name: "Google Chrome", brewCask: "google-chrome", masId: nil, categories: ["browser"]),
    CatalogApp(id: "1password", name: "1Password", brewCask: "1password", masId: nil, categories: ["security"]),
    // Additional apps to round out the catalog
    CatalogApp(id: "firefox", name: "Firefox", brewCask: "firefox", masId: nil, categories: ["browser"]),
    CatalogApp(id: "brave", name: "Brave Browser", brewCask: "brave-browser", masId: nil, categories: ["browser"]),
    CatalogApp(id: "bitwarden", name: "Bitwarden", brewCask: "bitwarden", masId: nil, categories: ["security"]),
    CatalogApp(id: "nordvpn", name: "NordVPN", brewCask: "nordvpn", masId: nil, categories: ["security"]),
    CatalogApp(id: "git", name: "Git", brewCask: nil, masId: nil, categories: ["developer"]),
    CatalogApp(id: "sourcetree", name: "Sourcetree", brewCask: "sourcetree", masId: nil, categories: ["developer"]),
    CatalogApp(id: "tower", name: "Tower", brewCask: "tower", masId: nil, categories: ["developer"]),
    CatalogApp(id: "paw", name: "RapidAPI (Paw)", brewCask: "rapidapi", masId: nil, categories: ["developer"]),
    CatalogApp(id: "proxyman", name: "Proxyman", brewCask: "proxyman", masId: nil, categories: ["developer"]),
    CatalogApp(id: "insomnia", name: "Insomnia", brewCask: "insomnia", masId: nil, categories: ["developer"]),
    CatalogApp(id: "sequel-pro", name: "Sequel Pro", brewCask: "sequel-pro", masId: nil, categories: ["developer"]),
    CatalogApp(id: "dbeaver", name: "DBeaver", brewCask: "dbeaver-community", masId: nil, categories: ["developer"]),
    CatalogApp(id: "intellij", name: "IntelliJ IDEA", brewCask: "intellij-idea", masId: nil, categories: ["developer"]),
    CatalogApp(id: "pycharm", name: "PyCharm", brewCask: "pycharm", masId: nil, categories: ["developer"]),
    CatalogApp(id: "webstorm", name: "WebStorm", brewCask: "webstorm", masId: nil, categories: ["developer"]),
    CatalogApp(id: "goland", name: "GoLand", brewCask: "goland", masId: nil, categories: ["developer"]),
    CatalogApp(id: "sublime", name: "Sublime Text", brewCask: "sublime-text", masId: nil, categories: ["developer"]),
    CatalogApp(id: "nova", name: "Nova", brewCask: "nova", masId: nil, categories: ["developer"]),
    CatalogApp(id: "transmit", name: "Transmit", brewCask: "transmit", masId: nil, categories: ["developer"]),
    CatalogApp(id: "cyberduck", name: "Cyberduck", brewCask: "cyberduck", masId: nil, categories: ["developer"]),
    CatalogApp(id: "linear", name: "Linear", brewCask: "linear-linear", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "craft", name: "Craft", brewCask: nil, masId: 1487937127, categories: ["productivity"]),
    CatalogApp(id: "things", name: "Things 3", brewCask: nil, masId: 904280696, categories: ["productivity"]),
    CatalogApp(id: "fantastical", name: "Fantastical", brewCask: "fantastical", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "todoist", name: "Todoist", brewCask: "todoist", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "trello", name: "Trello", brewCask: "trello", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "asana", name: "Asana", brewCask: "asana", masId: nil, categories: ["productivity"]),
    CatalogApp(id: "microsoft-word", name: "Microsoft Word", brewCask: nil, masId: 462054704, categories: ["productivity"]),
    CatalogApp(id: "microsoft-excel", name: "Microsoft Excel", brewCask: nil, masId: 462058435, categories: ["productivity"]),
    CatalogApp(id: "microsoft-powerpoint", name: "Microsoft PowerPoint", brewCask: nil, masId: 462062816, categories: ["productivity"]),
    CatalogApp(id: "adobe-acrobat", name: "Adobe Acrobat Reader", brewCask: "adobe-acrobat-reader", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "pdf-expert", name: "PDF Expert", brewCask: nil, masId: 1055273043, categories: ["utilities"]),
    CatalogApp(id: "acorn", name: "Acorn", brewCask: nil, masId: 1233861775, categories: ["designer"]),
    CatalogApp(id: "pixelmator", name: "Pixelmator Pro", brewCask: nil, masId: 1289583905, categories: ["designer"]),
    CatalogApp(id: "affinity-designer", name: "Affinity Designer", brewCask: "affinity-designer", masId: nil, categories: ["designer"]),
    CatalogApp(id: "affinity-photo", name: "Affinity Photo", brewCask: "affinity-photo", masId: nil, categories: ["designer"]),
    CatalogApp(id: "zeplin", name: "Zeplin", brewCask: "zeplin", masId: nil, categories: ["designer"]),
    CatalogApp(id: "abstract", name: "Abstract", brewCask: "abstract", masId: nil, categories: ["designer"]),
    CatalogApp(id: "telegram", name: "Telegram", brewCask: "telegram", masId: nil, categories: ["communication"]),
    CatalogApp(id: "whatsapp", name: "WhatsApp", brewCask: "whatsapp", masId: nil, categories: ["communication"]),
    CatalogApp(id: "signal", name: "Signal", brewCask: "signal", masId: nil, categories: ["communication"]),
    CatalogApp(id: "microsoft-teams", name: "Microsoft Teams", brewCask: "microsoft-teams", masId: nil, categories: ["communication"]),
    CatalogApp(id: "skype", name: "Skype", brewCask: "skype", masId: nil, categories: ["communication"]),
    CatalogApp(id: "twist", name: "Twist", brewCask: "twist", masId: nil, categories: ["communication"]),
    CatalogApp(id: "screenflow", name: "ScreenFlow", brewCask: "screenflow", masId: nil, categories: ["content-creator"]),
    CatalogApp(id: "final-cut", name: "Final Cut Pro", brewCask: nil, masId: 424389933, categories: ["content-creator"]),
    CatalogApp(id: "logic-pro", name: "Logic Pro", brewCask: nil, masId: 634148309, categories: ["content-creator"]),
    CatalogApp(id: "garageband", name: "GarageBand", brewCask: nil, masId: 682658836, categories: ["content-creator"]),
    CatalogApp(id: "audacity", name: "Audacity", brewCask: "audacity", masId: nil, categories: ["content-creator"]),
    CatalogApp(id: "gyroflow", name: "Gyroflow Toolbox", brewCask: nil, masId: 1668498538, categories: ["content-creator"]),
    CatalogApp(id: "proxyman-ios", name: "Proxyman iOS Mirror", brewCask: nil, masId: nil, categories: ["developer"]),
    CatalogApp(id: "amplitude", name: "Amplitude Analytics", brewCask: nil, masId: nil, categories: ["data-science"]),
    CatalogApp(id: "jupyter", name: "JupyterLab Desktop", brewCask: "jupyterlab", masId: nil, categories: ["data-science"]),
    CatalogApp(id: "rstudio", name: "RStudio", brewCask: "rstudio", masId: nil, categories: ["data-science"]),
    CatalogApp(id: "tableau", name: "Tableau Public", brewCask: "tableau-public", masId: nil, categories: ["data-science"]),
    CatalogApp(id: "datagrip", name: "DataGrip", brewCask: "datagrip", masId: nil, categories: ["data-science"]),
    CatalogApp(id: "metabase", name: "Metabase", brewCask: "metabase", masId: nil, categories: ["data-science"]),
    CatalogApp(id: "bartender", name: "Bartender", brewCask: "bartender", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "amphetamine", name: "Amphetamine", brewCask: nil, masId: 937984704, categories: ["utilities"]),
    CatalogApp(id: "appcleaner", name: "AppCleaner", brewCask: "appcleaner", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "istat-menus", name: "iStat Menus", brewCask: "istat-menus", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "bettertouchtool", name: "BetterTouchTool", brewCask: "bettertouchtool", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "macs-fan-control", name: "Macs Fan Control", brewCask: "macs-fan-control", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "the-unarchiver", name: "The Unarchiver", brewCask: nil, masId: 425424353, categories: ["utilities"]),
    CatalogApp(id: "keka", name: "Keka", brewCask: "keka", masId: nil, categories: ["utilities"]),
    CatalogApp(id: "mosaic", name: "Mosaic", brewCask: nil, masId: 1419490886, categories: ["utilities"]),
    CatalogApp(id: "keystroke-pro", name: "Keystroke Pro", brewCask: nil, masId: 1572206224, categories: ["utilities"]),
    CatalogApp(id: "proxifier", name: "Proxifier", brewCask: "proxifier", masId: nil, categories: ["security"]),
    CatalogApp(id: "little-snitch", name: "Little Snitch", brewCask: "little-snitch", masId: nil, categories: ["security"]),
    CatalogApp(id: "mullvad", name: "Mullvad VPN", brewCask: "mullvadvpn", masId: nil, categories: ["security"]),
    CatalogApp(id: "authy", name: "Authy", brewCask: "authy", masId: nil, categories: ["security"]),
]

let appCategories = ["all", "developer", "designer", "productivity", "content-creator", "data-science", "communication", "utilities", "browser", "security", "ai"]
